#!/bin/sh

# Exercise some basics: create a git repo, clean up when
# we're done.
. ./test-lib.sh

# git init that repo and chdir to it
git init temprepo
cd temprepo

# run some commands, none of which should fail.
git status
ls .git

# use the shell "test" operator together with "set -e" to make some
# "assertions"
[ -d .git/hooks ]
