#!/bin/sh

# Quick functional test. Create a bare repo and clone
# it. Set up dispatch in both with install-dispatch.
# Ensure symlinks were created as expected.

git init --bare upstream.git
git clone upstream.git clone
(cd clone; touch foo; git add foo; git commit -m "initial commit"; git push)

# Run install-dispatch in bare upstream
(cd upstream.git; "$mgh_build_dir/install-dispatch")
test upstream.git/hooks/update -ef "$mgh_build_dir/dispatch"

# Run install-dispatch in clone
(cd clone; "$mgh_build_dir/install-dispatch")
test clone/.git/hooks/pre-commit -ef "$mgh_build_dir/dispatch"
